### ISSUE TITLE
IP Patterns rules throws exception when using it with MicronautAwsProxyRequest.java

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-security#1020]
### Issue description

```
10:00:40.995 [qtp1561745898-68] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: hostname can't be null
java.lang.IllegalArgumentException: hostname can't be null
	at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getRemoteAddress(MicronautAwsProxyRequest.java:226)
	at io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:82)
	at io.micronaut.security.filters.SecurityFilter.lambda$checkRules$6(SecurityFilter.java:168)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:376)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onComplete(ReactorSubscriber.java:71)
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
```

**Comment by sdelamo** [comment]
Clsoed via https://github.com/micronaut-projects/micronaut-security/pull/1022
