### ISSUE TITLE
Bean definition [io.micronaut.security.token.jwt.validator.JwtTokenValidator] could not be loaded

### ISSUE THREAD

**Issue by carl-mastrangelo** [micronaut-projects/micronaut-security#1034]
### Expected Behavior

More lenient parsing of openid metadata

### Actual Behaviour

Unable to parse OpenID metadata when an optional field `device_authorization_endpoint` is present.

### Steps To Reproduce

Using Micronaut Security with Google Oauth results in a Bean not being constructible.    The stack trace on boot looks like:

```
14:49:58.850 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.security.token.jwt.validator.JwtTokenValidator] could not be loaded: JSON Processing Exception parsing issuer URL returned JSON https://accounts.google.com
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.security.token.jwt.validator.JwtTokenValidator] could not be loaded: JSON Processing Exception parsing issuer URL returned JSON https://accounts.google.com
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1938)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: JSON Processing Exception parsing issuer URL returned JSON https://accounts.google.com
	at io.micronaut.security.oauth2.client.OpenIdClientFactory.lambda$openIdConfiguration$0(OpenIdClientFactory.java:123)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.micronaut.security.oauth2.client.OpenIdClientFactory.openIdConfiguration(OpenIdClientFactory.java:109)
	at io.micronaut.security.oauth2.client.$OpenIdClientFactory$OpenIdConfiguration0$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:755)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:132)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
	at io.micronaut.inject.provider.BeanProviderDefinition$1.get(BeanProviderDefinition.java:69)
	at io.micronaut.security.oauth2.client.JwksUriSignatureFactory.createJwksUriSignature(JwksUriSignatureFactory.java:50)
	at io.micronaut.security.oauth2.client.$JwksUriSignatureFactory$CreateJwksUriSignature0$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:755)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:132)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3685)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3591)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1376)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBeansOfType(AbstractInitializableBeanDefinition.java:2132)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractInitializableBeanDefinition.java:1422)
	at io.micronaut.security.token.jwt.validator.$JwtTokenValidator$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2664)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1932)
	... 7 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "device_authorization_endpoint" (class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata), not marked as ignorable (43 known properties: "claims_locales_supported", "end_session_endpoint", "check_session_iframe", "grant_types_supported", "default_grant_types_supported", "userinfo_encryption_alg_values_supported", "userinfo_encryption_enc_values_supported", "scopes_supported", "claims_parameter_supported", "revocation_endpoint_auth_methods_supported", "subject_types_supported", "revocation_endpoint", "introspection_endpoint", "authorization_endpoint", "request_object_signing_alg_values_supported", "acr_values_supported", "response_modes_supported", "jwks_uri", "claim_types_supported", "claims_supported", "op_tos_uri", "request_parameter_supported", "response_types_supported", "token_endpoint_auth_methods_supported", "introspection_endpoint_auth_methods_supported", "code_challenge_methods_supported", "uri_locales_supported", "require_request_uri_registration", "id_token_signing_alg_values_supported", "issuer", "op_policy_uri", "request_object_encryption_alg_values_supported", "request_object_encryption_enc_values_supported" [truncated]])
 at [Source: (byte[])"{
 "issuer": "https://accounts.google.com",
 "authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
 "device_authorization_endpoint": "https://oauth2.googleapis.com/device/code",
 "token_endpoint": "https://oauth2.googleapis.com/token",
 "userinfo_endpoint": "https://openidconnect.googleapis.com/v1/userinfo",
 "revocation_endpoint": "https://oauth2.googleapis.com/revoke",
 "jwks_uri": "https://www.googleapis.com/oauth2/v3/certs",
 "response_types_supported": [
  "code",
  "tok"[truncated 780 bytes]; line: 4, column: 36] (through reference chain: io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata["device_authorization_endpoint"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3723)
	at io.micronaut.jackson.databind.JacksonDatabindMapper.readValue(JacksonDatabindMapper.java:119)
	at io.micronaut.security.oauth2.client.OpenIdClientFactory.lambda$openIdConfiguration$0(OpenIdClientFactory.java:117)
	... 34 common frames omitted
```

### Environment Information

JDK 17

### Version

3.5.0

**Comment by carl-mastrangelo** [comment]
I believe this was triggered by a (shared) ObjectMapper being marked to fail on unknown properties.   I can probably work to change this back in our code, though I feel the objectmapper / reader for Micronaut security could be a little more explicit about how it reads JSON.  I'm happy to send a PR to fix.

**Comment by sdelamo** [comment]
Do you have a sample app @carl-mastrangelo ?
