### ISSUE TITLE
Serialization of Authentication object into Redis session no longer works

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-security#1038]
### Expected Behavior

Serialization of attributes into Redis session works as before.

### Actual Behaviour

It somehow does not populate attributes into `Authentication` object:

```
Unexpected error occurred: null
java.lang.NullPointerException: null
	at java.util.HashMap.putMapEntries(HashMap.java:497)
	at java.util.HashMap.<init>(HashMap.java:486)
	at io.micronaut.security.authentication.ClientAuthentication.getAttributes(ClientAuthentication.java:64)
	at xxx.server.utils.extensions.AuthenticationExtensionsKt.getAccountId(AuthenticationExtensions.kt:11)
	at xxx.server.controllers.api.SessionController.getSession(SessionController.kt:36)
	at xxx.server.controllers.api.$SessionController$Definition$Intercepted.$$access$$getSession(Unknown Source)
	at xxx.server.controllers.api.$SessionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:196)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at xxx.server.controllers.api.$SessionController$Definition$Intercepted.getSession(Unknown Source)
	at xxx.server.controllers.api.$SessionController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

### Steps To Reproduce

Micronaut team has a sample application in `micronaut-graal-tests`, which can be simply modified to reproduci this behaviour: https://github.com/micronaut-graal-tests/micronaut-security-session-graal

Append to `application.yml`:

```yaml
---
redis:
  url: redis://127.0.0.1:6379
micronaut:
  session:
    http:
      redis:
        enabled: true
```

Add dependency to `build.gradle`:

```kotlin
implementation("io.micronaut.redis:micronaut-redis-lettuce")
```

You need to have Redis running on specified url for this test.

### Environment Information

GraalVM 22.1

### Version

3.5.1

**Comment by morki** [comment]
More information here: https://github.com/micronaut-projects/micronaut-security/pull/890#issuecomment-1153642049

**Comment by yawkat** [comment]
Are you sure this is a regression? I tested with security 3.5 and it still broke the same way. In which version did this work?

**Comment by morki** [comment]
Before this commit https://github.com/micronaut-projects/micronaut-security/commit/38714d1ff58a49227bf489fd64c9dac914b96bbd

**Comment by morki** [comment]
Before that commit, adding `TypeHint` or `ReflectiveAccess` made it work, but after that commit, there is no more solution to make it work. See description of https://github.com/micronaut-projects/micronaut-security/pull/890

**Comment by yawkat** [comment]
Which branch on micronaut-security-session-graal is that? I just tested 3.2.x also, which has security 3.2.3 which does not include that commit, and it produces the same NPE.

**Comment by morki** [comment]
Branch 3.0.x is working, I will try others.

**Comment by morki** [comment]
Branch 3.1.x is not working, so it is something in between those two.

**Comment by morki** [comment]
Sorry, it was my fault that i thought it was that referenced commit that created the problem, it seems it was a version before that.

**Comment by morki** [comment]
When I did diff between those branches of `micronaut-security`, there seems to be no change that can do this, I will dig deeper.

**Comment by yawkat** [comment]
the regression happened because prior to 3.1.x the request context was not available in the lettuce reactive handler. My guess is that this changed in one of @dstepanov's improvements to reactive context propagation. I'm not going to bother tracking down the specific change, since it's certainly better for the request context. I'll work on a fix on the security side instead.
