### ISSUE TITLE
Exception loading JWK URL (behind a proxy corporate)

### ISSUE THREAD

**Issue by elfelli** [micronaut-projects/micronaut-security#1048]
### Expected Behavior

Validate a JWT behind a proxy corporate 

### Actual Behaviour

I'm trying to configure AKHQ (0.21.0) based on micronaut v3.0.1 with okta oauth2. (okta is accessible only with a proxy corporate )

But i got a TimeoutException when trying to load JWKS URL behind the proxy 

micronaut:
  http:
    client:
      proxy-type: HTTP
      proxy-address: proxy.company.net:8080

https://github.com/micronaut-projects/micronaut-security/blob/963eabd8bcae21f81ed3679cb0c3215abdf65846/security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java#L166

it seem that the **load function** is not using the proxy config micronaut.http.client....
Authenticate against authentication providers is OK with proxy config 
JWT generation is OK ( token is valid i checked it manually)
But micronaut security fail when trying to validate JWT

**a work around** is to override jwks-uri: https://company.okta-emea.com/oauth2/aus2wqdfqfqkr0i7/v1/keys to mirror the json response under a direct access url without proxy 

TRACE LOG

9m Starting health monitor check
2022-06-30 08:57:17,416 ^[[1;31mERROR^[[0;39m ^[[35mpGroup-1-5^[[0;39m ^[[36m.m.s.t.j.s.j.JwksSignature^[[0;39m Exception loading JWK from [https://company.okta-emea.com/oauth2/auswzoolfffeCkr0i7/v1/keys](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcompany.okta-emea.com%2Foauth2%2FauswzoolfffeCkr0i7%2Fv1%2Fkeys&data=05%7C01%7Ceslem.felli%40externe.grdf.fr%7Cae45bdde3e4e4563a74908da5a678521%7Cfbbe061c9b3d4c4495e7714e319b60f6%7C1%7C0%7C637921697901813093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Pqv7Smj%2FZYbEOQ9QAkbXiRKVdqbYOBVVJ7oEI2%2BejGk%3D&reserved=0). The JwksSignature will not be used to verify a JWT if further refresh attempts fail

java.net.ConnectException: Connexion terminée par expiration du délai d'attente (Connection timed out)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
at java.base/java.net.Socket.connect(Socket.java:609)
at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
at java.base/sun.net.www.protocol.https.HttpsClient.(HttpsClient.java:265)
at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)

;39m JWT validation failed
io.micronaut.security.authentication.AuthenticationException: JWT validation failed
at io.micronaut.security.authentication.AuthenticationResponse.exception(AuthenticationResponse.java:121)
at io.micronaut.security.oauth2.endpoint.authorization.response.DefaultOpenIdAuthorizationResponseHandler.lambda$createAuthenticationResponse$1(DefaultOpenIdAuthorizationResponseHandler.java:171)
at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94)
at reactor.core.publisher.Flux.subscribe(Flux.java:8402)
at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onNext(FluxSwitchMap.java:236)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.drain(FluxSwitchMap.java:355)
at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.innerNext(FluxSwitchMap.java:413)
at reactor.core.publisher.FluxSwitchMap$SwitchMapInner.onNext(FluxSwitchMap.java:512)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onNext(WebMetricsPublisher.java:180)

Best Regards

### Steps To Reproduce

micronaut:
  http:
    client:
      proxy-type: HTTP
      proxy-address: proxy.company.net:8080
  security:
    enabled: true
    # OIDC authentication configuration
    oauth2:
      enabled: true
      clients:
        okta:
          scopes:
            - openid
            - profile
            - akhq_groups
          client-id: <****>
          client-secret: <*****>
          openid:
            issuer: https://company.okta-emea.com/oauth2/aus2wqdfqfqkr0i7
            configuration-path: /.well-known/oauth-authorization-server
            jwks-uri: https://company.okta-emea.com/oauth2/aus2wqdfqfqkr0i7/v1/keys

trying to validate JWT behind proxy 

### Environment Information

-RHEL 7
-JAVA 11

### Version

3.0.1

**Comment by geigervlad** [comment]
i have the same issue. Are there some news related this topic?

**Comment by geigervlad** [comment]
the only valid option I see here is to inject the keys into the container:
https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#staticJwks

**Comment by elfelli** [comment]
> i have the same issue. Are there some news related this topic?

Hello , on my cas i just added a proxy configuration on external file past into java execution args  (proxy and no_proxy , port ..) 
something like ->
PROXY_HOST=corporate-proxy.net
PROXY_PORT=8080
NON_PROXY_HOST="localhost,127.0.0.1|*.company.net|10.*.*.*"



JAVA_OPTS=(
    "-DsocksNonProxyHosts=\"${NON_PROXY_HOST}\""
    "-DsocksProxyHost=${PROXY_HOST}"
    "-DsocksProxyPort=${PROXY_PORT}"
    "-Dhttp.nonProxyHosts=\"${NON_PROXY_HOST}\""
    "-Dhttp.proxyHost=${PROXY_HOST}"
    "-Dhttp.proxyPort=${PROXY_PORT}"
    "-Dhttps.nonProxyHosts=\"${NON_PROXY_HOST}\""
    "-Dhttps.proxyHost=${PROXY_HOST}"
    "-Dhttps.proxyPort=${PROXY_PORT}"
    "-Xms2g" "-Xmx2g" "-server" "-Djava.net.preferIPv4Stack=true" "-XX:+PrintCommandLineFlags"
)

then start the jar with this args ..
nohup java "${JAVA_OPTS[@]}" -jar ${JAR_FILE} "${PROPS_OPTS[@]}" ......


this should handle properly the proxy

**Comment by geigervlad** [comment]
It worked thanks! I'm gonna post the whole solution(maybe it will help someone)

Kontext: I am using the helm chart and configured it as follows(with the help from @elfelli )

`akhq:
  extraEnv:
    - name: JAVA_OPTS
      value: "-DsocksProxyHost=CHANGEME -DsocksProxyPort=CHANGEME -Dhttps.proxyHost=CHANGEME  -Dhttps.proxyPort=CHANGEME -Dhttp.proxyHost=CHANGEME  -Dhttp.proxyPort=CHANGEME"
  configuration:
    micronaut:
      http:
        client:
          proxy-type: "HTTP"
          proxy-address: "CHANGEME_HOST:CHANGEME_PORT"
          proxyType: "HTTP"
          proxyAddress: "CHANGEME_HOST:CHANGEME_PORT"
      security:
        enabled: true
        oauth2:
          enabled: true
          clients:
            oidc:
              client-id: "${CLIENT_ID}"
              client-secret: "${CLIENT_SECRET}"
              openid:
                issuer: "CHANGEME"
                callback-uri: "CHANGEME"
        token:
          jwt:
            signatures:
              secret:
                generator:
                  secret: "${JTW_SIGNATURE_SECRET}"
        redirect:
            login-success:  "/ui"
    akhq:
      server:
        access-log:
          enabled: false
          name: org.akhq.log.access
      security:
        default-group: no-roles
        oidc:
          enabled: true
          providers:
            oidc:
              label: "Login with OIDC"
              default-group: reader
              username-field: preferred_username
              groups-field: roles
`

**Comment by sdelamo** [comment]
another option would be to remove `JWKSet.load(new URL(url));`  and offer an API based on an Micronaut HTTP Client.

**Comment by sdelamo** [comment]
@jeremyg484 lets try to replace https://github.com/micronaut-projects/micronaut-security/blob/master/security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/DefaultJwkSetFetcher.java#L65 with something like: https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/endpoint/token/request/DefaultTokenEndpointClient.java#L65
