### ISSUE TITLE
SecurityFilter throws NullpointerException when debug is enabled

### ISSUE THREAD

**Issue by aprietop** [micronaut-projects/micronaut-security#1278]
### Expected Behavior

A NullPointerException should not be thrown when debug is enabled

### Actual Behaviour

When logger level is set to `debug` or higher and at least one attribute is `null` the following exception is thrown:
```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
	at io.micronaut.security.filters.SecurityFilter.lambda$logAuthenticationAttributes$3(SecurityFilter.java:145)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1625)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1650)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.micronaut.security.filters.SecurityFilter.logAuthenticationAttributes(SecurityFilter.java:146)
	at io.micronaut.security.filters.SecurityFilter.createResponse(SecurityFilter.java:135)
	at io.micronaut.security.filters.SecurityFilter.lambda$doFilter$1(SecurityFilter.java:115)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher$1.request(Publishers.java:563)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:964)
	at io.micronaut.core.async.publisher.Publishers$JustPublisher.subscribe(Publishers.java:553)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8522)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRouteMatch(MicronautLambdaContainerHandler.java:371)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.lambda$handleRequest$2(MicronautLambdaContainerHandler.java:333)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:325)
	at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.handleRequest(MicronautLambdaContainerHandler.java:105)
	at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:205)
	at io.micronaut.function.aws.proxy.MicronautLambdaHandler.handleRequest(MicronautLambdaHandler.java:69)
```

### Steps To Reproduce

Please take a look at the example application.

To replicate the issue set `io.micronaut.security` logging level to `debug` or higer   

```
<logger name="io.micronaut.security" level="DEBUG"/>
````

### Environment Information

- Mac OS / Linux
- JDK17
- Micronaut Application - AWS Lambda custom runtime

### Example Application

https://github.com/aprietop/micronaut-lambda-nullpointer-debug-sample

### Version

3.7.5

**Comment by aprietop** [comment]
Hi @sdelamo,  

I have created this PR to address this issue https://github.com/micronaut-projects/micronaut-security/pull/1279
Could you please take a look?

Thank you.

**Comment by sdelamo** [comment]
3..9.5 and 3.10.1 include your patch.

**Comment by aprietop** [comment]
Great! Thanks @sdelamo

**Comment by aprietop** [comment]
@sdelamo I'm having the issue with `micronaut-security` 3.11.0
