### ISSUE TITLE
oauth that worked in Micronaut 4.6.1 broken in 4.6.2 release

### ISSUE THREAD

**Issue by PeterFokkinga** [micronaut-projects/micronaut-security#1808]
### Expected Behavior

An Oauth authentication flow that works in 4.6.1 should still work in 4.6.2 

### Actual Behaviour

(strava is my Oauth provider)
GET /oauth/login/strava works
GET /oauth/callback/strava?state=ey...&code=c4...&scope=activity:read_all,read never gives a response nor reaches my implementation of OauthAuthenticationMapper

Note: the only difference is `version "4.6.2"` instead of `version "4.6.1"` in the micronaut section of my build.gradle

### Steps To Reproduce

In my logs I see
```
20:24:44.088 [default-nioEventLoopGroup-1-2] DEBUG n.r.LocaleFilter          - trace: GET /oauth/login/strava
20:24:44.088 [default-nioEventLoopGroup-1-2] INFO  n.r.LocaleFilter          - no session
20:24:44.099 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.r.DefaultOauthController - Received login request for provider [strava]
20:24:44.102 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.c.DefaultOauthClient - Starting authorization code grant flow to provider [strava]. Redirecting to [https://www.strava.com/oauth/authorize]
20:24:44.116 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.e.a.r.DefaultAuthorizationRedirectHandler - Built the authorization URL [https://www.strava.com/oauth/authorize?scope=activity%3Aread_all%2Cread&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A9002%2Foauth%2Fcallback%2Fstrava&state=ey...&client_id=xxxx]
20:24:44.406 [default-nioEventLoopGroup-1-2] DEBUG n.r.LocaleFilter          - trace: GET /oauth/callback/strava?state=ey...&code=12...&scope=activity:read_all,read
20:24:44.407 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.r.DefaultOauthController - Received callback from oauth provider [strava]
20:24:44.408 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.c.DefaultOauthClient - Received a successful authorization response from provider [strava]
20:24:44.408 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.e.a.r.DefaultOauthAuthorizationResponseHandler - Validating state found in the authorization response from provider [strava]
20:24:44.414 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.e.t.r.DefaultTokenEndpointClient - Sending request to token endpoint [https://www.strava.com/oauth/token]
20:24:44.416 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.e.t.r.DefaultTokenEndpointClient - The token endpoint supports [[client_secret_basic]] authentication methods
20:24:44.416 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.e.t.r.DefaultTokenEndpointClient - Using client_secret_basic authentication. Adding an Authorization header
20:24:44.500 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.c.c.p.ClientCredentialsHttpClientFilter - Did not find any OAuth 2.0 client which should decorate the request with an access token received from client credentials request
20:24:44.865 [default-nioEventLoopGroup-1-3] ERROR r.c.p.Operators           - Operator called default onErrorDropped
java.lang.NullPointerException: Cannot invoke "io.micronaut.security.oauth2.endpoint.token.response.TokenError.toString()" because "this.error" is null
	at io.micronaut.security.oauth2.endpoint.token.response.TokenErrorResponse.toString(TokenErrorResponse.java:92)
	at io.micronaut.http.client.exceptions.HttpClientErrorDecoder.getMessage(HttpClientErrorDecoder.java:57)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.micronaut.http.client.exceptions.HttpClientResponseException.getMessage(HttpClientResponseException.java:70)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:67)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:94)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:51)
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:145)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:424)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:419)
	at ch.qos.logback.classic.Logger.error(Logger.java:535)
	at io.micronaut.http.server.RouteExecutor.logException(RouteExecutor.java:280)
	at io.micronaut.http.server.RouteExecutor.createDefaultErrorResponse(RouteExecutor.java:212)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.writeResponse(RoutingInBoundHandler.java:244)
	at io.micronaut.http.server.netty.NettyRequestLifecycle.lambda$handleNormal$0(NettyRequestLifecycle.java:107)
	at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl$1.onError(ReactorExecutionFlowImpl.java:116)
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [5 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [8 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [5 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [5 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [9 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [9 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [27 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [9 skipped]
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onError(ReactivePropagation.java:115) [9 skipped]
	at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.lambda$onError$2(ClientServerRequestTracingPublisher.java:65)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:49)
	at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onError(ClientServerRequestTracingPublisher.java:65)
	at io.micronaut.http.client.netty.ForwardingSubscriber.onError(ForwardingSubscriber.java:50) [16 skipped]
	at io.micronaut.http.client.netty.NettyFuturePublisher$1.lambda$request$0(NettyFuturePublisher.java:57)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.forwardResponseToPromise(DefaultHttpClient.java:2211)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2181)
	at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.channelReadInstrumented(DefaultHttpClient.java:2149)
	at io.micronaut.http.client.netty.SimpleChannelInboundHandlerInstrumented.channelRead0(SimpleChannelInboundHandlerInstrumented.java:46)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:981)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.fireChildRead(AbstractHttp2StreamChannel.java:601)
	at io.netty.handler.codec.http2.Http2MultiplexHandler.channelRead(Http2MultiplexHandler.java:193)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.http2.Http2FrameCodec.onHttp2Frame(Http2FrameCodec.java:717)
	at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onDataRead(Http2FrameCodec.java:656)
	at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:34)
	at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:320)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:409)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:244)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:164)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:186)
	at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:61)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:391)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:451)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1495)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1358)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1407)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 [1 skipped
```
(all reactor.core.* lines left out and I redacted some in case it )

### Environment Information

MacOS 14.4.1 on Apple Silicon using Eclipse Temurin 21.0.2 SDK

### Version

4.6.2

**Comment by sdelamo** [comment]
@PeterFokkinga do you have a sample app? could it be that https://www.strava.com does not populate the `ErrorResponse::error`?

**Comment by sdelamo** [comment]
@PeterFokkinga does Strava support `.well-known/openid-configuration`?

can you paste you Oauth2 Configuration? - skip the client secret and client d of course.

**Comment by PeterFokkinga** [comment]
@sdelamo here is the Oauth2 config:
```
    oauth2:
      clients:
        strava:
          client-id: "${STRAVA_CLIENT_ID:0}"
          client-secret: "${STRAVA_CLIENT_SECRET:secret}"
          authorization:
            url: https://www.strava.com/oauth/authorize
          scopes:
            - activity:read_all,read
          token:
            url: https://www.strava.com/oauth/token
            auth-method: CLIENT_SECRET_POST
```
I don't think they support `.well-known/openid-configuration`

**Comment by sdelamo** [comment]
I think the issue is the Strava API response for an error in the token endpoint is something like this: 

```json
{"message":"Bad Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}
```

which is not compliant to [RFC 6749 Access Token Error Response](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2). We tried to bind their response to `TokenErroResponse`. 

I have an example of a working example with 4.6.2:  https://github.com/sdelamo/micronaut-oauth2-oidc-strava

![CleanShot 2024-10-01 at 10 57 03](https://github.com/user-attachments/assets/b0423e10-d364-437e-9f6d-1bd3ae9f727d)


I am able to reproduce the error if I don't create a valid token request, for example by commenting: 

```
#micronaut.security.oauth2.clients.strava.token.authentication-method=client_secret_post
```

I have the same behaviour with 4.6.1 or 4.6.2. 

When are you getting these errors?

**Comment by sdelamo** [comment]
@PeterFokkinga from you logs it seems you are using: 

`client_secret_basic`

> 20:24:44.416 [default-nioEventLoopGroup-1-2] TRACE i.m.s.o.e.t.r.DefaultTokenEndpointClient - Using client_secret_basic authentication. Adding an Authorization header

It seems you should be using: `client_secret_post` instead

**Comment by PeterFokkinga** [comment]
@sdelamo I think you found the cause, thank you for looking into it!

In 4.6.1 IntelliJ suggests `auth-method` as the property in the oauth configuration (see the config I posted earlier). Now with 4.6.2 it suggests both  `auth-method` (type AuthenticationMethod, an enum) and `authentication-method`(String). And indeed, when I add `authentication-method=client_secret_post` it works again.

Not happy with this change:
1. this is a 0.0.1 release, it should not break existing configurations
2. there is no mention in the release notes, not even in "Full Changelog"
3. `auth-method` is (still) in the [latest documentation](https://micronaut-projects.github.io/micronaut-security/latest/guide/) without  even mentioning `authentication-method`
4. using an enum like AuthenticationMethod (now marked deprecated) allows auto-complete of a property in an IDE; a String does not, so this makes life harder for developers

**Comment by sdelamo** [comment]
> @sdelamo I think you found the cause, thank you for looking into it!
> 
> In 4.6.1 IntelliJ suggests `auth-method` as the property in the oauth configuration (see the config I posted earlier). Now with 4.6.2 it suggests both `auth-method` (type AuthenticationMethod, an enum) and `authentication-method`(String). And indeed, when I add `authentication-method=client_secret_post` it works again.
> 
> Not happy with this change:
> 
> 1. this is a 0.0.1 release, it should not break existing configurations
> 2. there is no mention in the release notes, not even in "Full Changelog"
> 3. `auth-method` is (still) in the [latest documentation](https://micronaut-projects.github.io/micronaut-security/latest/guide/) without  even mentioning `authentication-method`
> 4. using an enum like AuthenticationMethod (now marked deprecated) allows auto-complete of a property in an IDE; a String does not, so this makes life harder for developers

It was not an intentional or capricious regression. We change to use a string instead of an enum because some servers return custom authentication methods, and we cannot support them with an enum. https://github.com/micronaut-projects/micronaut-security/pull/1790/files

I am going to explore if I can mitigate the transition for others to avoid the pain you experienced.

**Comment by sdelamo** [comment]
@PeterFokkinga this should fix it https://github.com/micronaut-projects/micronaut-security/pull/1818. Thanks for reporting and sorry for the regression.
