### ISSUE TITLE
propagation not working when using @Client!?

### ISSUE THREAD

**Issue by duclad** [micronaut-projects/micronaut-security#185]
I have this situation:
Two microservices: gateway and people, consul used for service discovery and a client defined in gateway that is calling the controller implemented in people microservice. For some reason, even of the login is successful and the two controllers separately works perfectly, when I try to use the `@Client` I get an Forbidden error.

Follow all the details:

1. for both microservices
                     micronautVersion=1.3.2
                     kotlinVersion=1.3.50

2. people microservice:

```yaml
micronaut:
  application:
    name: people
  server:
    port: -1
#  router:
#    static-resources:
#      swagger:
#        paths: classpath:META-INF/swagger
#        mapping: /swagger/**
#  config-client:
#    enabled: true
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            validation:
              secret: pleaseChangeThisSecretForANewOne
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:172.20.238.5}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
```

```java
@Controller("/people")
class PeopleController {
    @Secured("isAuthenticated()")
    @Produces(MediaType.TEXT_PLAIN)
    @Get("/{uuid}")
    fun getPerson(uuid: String): Single<String> {
        return Single.just("Gogu")
    }
}
```
3. gateway microservice
```yaml
micronaut:
  application:
    name: gateway
  server:
    port: 8080
#  router:
#    static-resources:
#      swagger:
#        paths: classpath:META-INF/swagger
#        mapping: /swagger/**
#  config-client:
#    enabled: true
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
      writer:
        header:
          enabled: true
      propagation:
        enabled: true
        service-id-regex: "people"
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:172.20.238.5}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
```

```java
@Client(id = "people")
interface PeopleClient {
    @Get("/people")
    fun getPerson(uuid: String): Single<String>
}
```

```java
@Controller("/people")
class PeopleController(private val usernameFetcher: PeopleClient) {
    @Secured(SecurityRule.IS_AUTHENTICATED)
    @Produces(MediaType.TEXT_PLAIN)
    @Get("/{uuid}")
    fun getPerson(uuid: String) = usernameFetcher.getPerson(uuid)
}
```

And when trying to call the api defined in gateway I get this error:

```java
11:52:02.125 [nioEventLoopGroup-1-10] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Forbidden
io.micronaut.http.client.exceptions.HttpClientResponseException: Forbidden
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1831)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1749)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:48)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Please, could someone point me to the mistake I make?

**Comment by duclad** [comment]
Found it!!!!

the Path of the client is missing the /{uuid}


so all good now...
