### ISSUE TITLE
IpPatterRules throws NPE

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-security#186]
When stress testing our service, after some time we get following exception.
No rules are configured in app.

micronaut 1.3.2 
micronaut-security-jwt 1.3.1

```
14:29:44.248 [nioEventLoopGroup-1-8] || ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: null
java.lang.NullPointerException: null
	at io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:97)
	at io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:147)
	at io.micronaut.security.filters.SecurityFilter.lambda$doFilterOnce$3(SecurityFilter.java:125)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:132)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onSuccess(MaybeToFlowable.java:70)
	at io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onSuccess(MaybeDoOnEvent.java:86)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmit(FlowableFlatMap.java:282)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:663)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FlowableSwitchIfEmpty.java:59)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FlowableSwitchIfEmpty.java:59)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscriptions.SubscriptionArbiter.setSubscription(SubscriptionArbiter.java:99)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onSubscribe(FlowableSwitchIfEmpty.java:51)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableScalarXMap$ScalarXMapFlowable.subscribeActual(FlowableScalarXMap.java:160)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.internal.subscriptions.EmptySubscription.complete(EmptySubscription.java:69)
	at io.reactivex.internal.operators.flowable.FlowableEmpty.subscribeActual(FlowableEmpty.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableScalarXMap$ScalarXMapFlowable.subscribeActual(FlowableScalarXMap.java:160)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:236)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by jameskleeh** [comment]
Can you debug it and tell me which part of `request.getRemoteAddress().getAddress().getHostAddress()` is null?

**Comment by vnesek** [comment]
Catching it in debugger and evaluating request.getRemoteAddress() returned null.

Additionally, patternList is initialized to a single pattern of "0.0.0.0" although I haven't setup any ip-patterns in application settings. 

Perhaps IpPatternsRule should be conditional on existence of micronaut.security.ip-patterns? 
I don't see any reason for it intercepting requests if not explicitly configured.

**Comment by julKali** [comment]
@vnesek what setup/features do you use?

**Comment by julKali** [comment]
I'm trying to reproduce your issue but I never get this exception. Can you elaborate a bit more about your project? Do you use any request interceptors? What does your stress test look like? How many iterations? Serial or parallel? Are you targeting localhost or 127.0.0.1?
Is it possible to create a project from scratch where you can reproduce the issue?

**Comment by vnesek** [comment]
I caught it with debugger (OSX Catalina). Tried with 127.0.0.1 and local IP address as well but no luck.

request instance was NettyHttpRequest

```
    @Override
    public InetSocketAddress getRemoteAddress() {
        return (InetSocketAddress) getChannelHandlerContext()
            .channel()
            .remoteAddress();
    }
```

channelHandlerContext was DefaultHandlerChannelHolder, it's handler was HttpRequestDecoder

channel was NioSocketChannel whose remoteAddress() is implemented in AbstractChannel

```
    @Override
    public SocketAddress remoteAddress() {
        SocketAddress remoteAddress = this.remoteAddress;
        if (remoteAddress == null) {
            try {
                this.remoteAddress = remoteAddress = unsafe().remoteAddress();
            } catch (Error e) {
                throw e;
            } catch (Throwable t) {
                // Sometimes fails on a closed socket in Windows.
                return null;
            }
        }
        return remoteAddress;
    }
```
I had brackpoints on throw e, and return null so it must be that line
```
this.remoteAddress = remoteAddress = unsafe().remoteAddress()
``` 
returns null without any exception

Contract for HttpRequest::getRemoteAddress is Non null, but it can return null in some cicumstances. 

Could you make IpPatternsRule conditional on existence of micronaut.security.ip-patterns or add null checks for remoter address before evaluating remote address?

**Comment by julKali** [comment]
Yeah this redirects to [here](https://github.com/netty/netty/blob/6c05d16967df5cadcebcc498223eec3f25bacf89/transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java#L291):
![image](https://user-images.githubusercontent.com/17690423/75439445-186dd000-595a-11ea-84ad-abac6f809fd5.png)

The JavaDoc for `java.net.Socket` says:
![image](https://user-images.githubusercontent.com/17690423/75439629-70a4d200-595a-11ea-857c-d22ad5ac61fa.png)

According to this description, the remote address gets cached by the socket ... which means the sockets that cause the NPEs were never connected in the first place ... I don't know how that can happen.

**Comment by vnesek** [comment]
Well... this javaChannel() is instance of sun.nio.ch.SocketChannelImpl and it's remoteAddress field is set.

This looks like a race in micronaut and/or netty.

**Comment by sdelamo** [comment]
If you are not using IP patterns you replace the bean with:

```
@Singleton
public class ReplacementIpPatternsRule extends IpPatternsRule {

    /**
     *
     * @param rolesFinder Roles Parser
     * @param securityConfiguration Security Configuration
     */
    public ReplacementIpPatternsRule(RolesFinder rolesFinder,
                                     SecurityConfiguration securityConfiguration) {
        super(rolesFinder, securityConfiguration);
    }

    @Override
    public SecurityRuleResult check(HttpRequest request, @Nullable RouteMatch routeMatch, @Nullable Map<String, Object> claims) {
        return SecurityRuleResult.UNKNOWN;
    }
}
```

**Comment by jameskleeh** [comment]
That shouldn't be necessary

**Comment by vnesek** [comment]
Haven't tested, but adding following annotation to class declaration should prevent instantiation.
```
@Requires(property = "micronaut.security.ip-patterns")
```

**Comment by ivarprudnikov** [comment]
In my specific case (v1.3.1) I got the error when running
```
$ sam local start-api --template sam-local.yaml
```

It failed to GET "/" and responded with 502 and stacktrace pointing to that NPE.

It was `micronaut.security.enabled = true` which I think messed things up as documentation states an interesting fact about `micronaut.security.ip-patterns`

> Allowed IP patterns. Default value (["0.0.0.0"])

As soon as I made sure `ip-patterns` are an empty array then it was responding locally as normal, I do not need those anyway, and it is odd that defaults include one pattern.

```
micronaut:
  security:
    enabled: true
    ip-patterns: []
```

**Comment by ashish-sharma09** [comment]
Any idea when 1.3.2 will be released containing the fix for this issue, we are frequently seeing this error in our application. Any timelines or plans shared here on this release will be super useful. Thanks in advance.

**Comment by ivarprudnikov** [comment]
Looks like they are going to leapfrog into v2 with the fix merged in [v2.0.0.M1](https://github.com/micronaut-projects/micronaut-security/releases/tag/v2.0.0.M1) although [1.4.x](https://github.com/micronaut-projects/micronaut-security/tree/1.4.x) branch was not released yet

**Comment by jameskleeh** [comment]
@ivarprudnikov This fix was done in the 1.3.x branch which means it will be applied to the next 1.3.x release and any future releases (including 1.4 and 2.0)

**Comment by traycho** [comment]
Has anybody tried this working with docker ?

```
sam-local_1    | java.lang.NullPointerException
sam-local_1    | 	at io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:101)
sam-local_1    | 	at io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:173)
sam-local_1    | 	at io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:218)
```
It seems getAddress() is returning null
```
String hostAddress = socketAddress.getAddress().getHostAddress();
```

**Comment by vanga** [comment]
I see this error during load testing even when I am on 1.3.2

```
4","level":"ERROR","level_value":40000,"stack_trace":"java.lang.NullPointerException: null\n\tat io.micronaut.security.rules.IpPatternsRule.check(IpPatternsRule.java:97)\n\tat io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:147)\n\tat io.micronaut.security.filters.SecurityFilter.lambda$doFilterOnce$4(SecurityFilter.java:126)\n\tat io.micronaut.security.filters.SecurityFilter$$Lambda$1123.000000003C0434F0.call(Unknown Source)\n\tat io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onComplete(MaybeToFlowable.java:80)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:100)\n\tat io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onComplete(MaybeDoOnEvent.java:115)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:100)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onComplete(FlowableElementAtMaybe.java:102)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:101)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.slowPath(FlowableFromIterable.java:255)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:124)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:117)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:55)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)\n\tat io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedMaybe.subscribeActual(RxInstrumentedMaybe.java:53)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4290)\n\tat io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14868)\n\tat io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)\n\tat io.micronaut.http.context.ServerRequestTracingPublisher$$Lambda$1129.000000003C045F10.run(Unknown Source)\n\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)\n\tat io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)\n\tat io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:153)\n\tat io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14918)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14865)\n\tat io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)\n\tat
```
