### ISSUE TITLE
OpenIdClientCondition causing circular bean reference

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-security#220]
The build is currently failing because `OpenIdClientCondition` has a circular reference.

```
4-19T20:06:58.9460784Z         java.lang.IllegalStateException: Recursive update
2020-04-19T20:06:58.9461053Z             at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1760)
2020-04-19T20:06:58.9461189Z             at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
2020-04-19T20:06:58.9461330Z             at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
2020-04-19T20:06:58.9461991Z             at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2249)
2020-04-19T20:06:58.9462129Z             at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2038)
2020-04-19T20:06:58.9462256Z             at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
```

**Comment by jameskleeh** [comment]
Should be resolved for 2.0
