### ISSUE TITLE
Oauth scopes lead to NullPointerException

### ISSUE THREAD

**Issue by t139n** [micronaut-projects/micronaut-security#225]
A NullPointerException occurs if scopes have been added to a oauth2 client in the application configuration.

Configuration using Auth0:
` scopes:
     - read:roles`

Exception:

`[nioEventLoopGroup-1-74] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: null
java.lang.NullPointerException: null
	at com.nimbusds.jwt.JWTParser.parse(JWTParser.java:58)
	at io.micronaut.security.token.jwt.validator.JwtTokenValidatorUtils.parseJwtIfValidSignature(JwtTokenValidatorUtils.java:216)
	at io.micronaut.security.oauth2.endpoint.token.response.validation.DefaultOpenIdTokenResponseValidator.validate(DefaultOpenIdTokenResponseValidator.java:81)
	at io.micronaut.security.oauth2.endpoint.authorization.response.DefaultOpenIdAuthorizationResponseHandler.lambda$null$0(DefaultOpenIdAuthorizationResponseHandler.java:118)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)`

**Comment by jameskleeh** [comment]
@t139n That could only happen if the provider is not returning a token. I would assume that means there is some problem on your end or the provider

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback. If you decide to pursue this further please let me know and I'll reopen
