### ISSUE TITLE
Trying to get an attribute from AttributesConvertibleValues raises NPE if attribute does not exist

### ISSUE THREAD

**Issue by ritikmishra** [micronaut-projects/micronaut-security#479]
To reproduce:
```java
import io.micronaut.configuration.security.ldap.context.AttributesConvertibleValues;
import io.micronaut.core.convert.ConversionContext;

import javax.naming.directory.BasicAttributes;

public class Scratch {
    public static void main(String[] args) {
        BasicAttributes attrs = new BasicAttributes("fruit", "apple");
        AttributesConvertibleValues convertibleValues = new AttributesConvertibleValues(attrs);
        
        // works as expected, returns Optional[apple]
        System.out.println(convertibleValues.get("fruit", ConversionContext.STRING));

        // throws NullPointerException, expected Optional.empty
        System.out.println(convertibleValues.get("vegetable", ConversionContext.STRING));
    }
}
```

Stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
	at io.micronaut.configuration.security.ldap.context.AttributesConvertibleValues.get(AttributesConvertibleValues.java:78)
	at com.uhg.ihr.provider.portal.auth.model.Scratch.main(Scratch.java:15)
```

https://github.com/micronaut-projects/micronaut-security/blob/39eef7d3d3cfe6a25ba957026d725a78b769cbb8/security-ldap/src/main/java/io/micronaut/configuration/security/ldap/context/AttributesConvertibleValues.java#L78

**Comment by sdelamo** [comment]
@ritikmishra thanks for reporting.
