### ISSUE TITLE
StackoverflowError after authenticate a user in LDAP

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-security#559]
There is an StackoverflowError after a user is authenticated against an LDAP server.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-security-ldap-graal`
- `cd micronaut-security-ldap-graal`
- `git checkout 2.3.x`
- Start LDAP in a docker container: `docker run -it --rm -p 389:389 pgarrett/ldap-alpine`
- `./gradlew run`

Send curl request:
```
curl -X POST -H "Content-Type: application/json" -d '{"username": "pgarrett", "password": "password"}' localhost:8080/login
```

Error:

```
7:08:53.827 [io-executor-thread-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Error encoding object [io.micronaut.security.authentication.UserDetails@6727605b] to JSON: Infinite recursion (StackOverflowError) (through reference chain: io.micronaut.security.authentication.UserDetails["userDetails"]->io.micronaut.security.authentication.UserDetails["userDetails"]->io.micronaut.security.authentication.UserDetails["userDetails"]-

...
...

>io.micronaut.security.authentication.UserDetails["userDetails"]->io.micronaut.security.authentication.UserDetails["userDetails"]->io.micronaut.security.authentication.UserDetails["userDetails"])
        at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.serialize(ReferenceTypeSerializer.java:386)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.serialize(ReferenceTypeSerializer.java:386)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.serialize(ReferenceTypeSerializer.java:386)

...
...

        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
ceTypeSerializer.java:386)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer.serialize(ReferenceTypeSerializer.java:386)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
Caused by: java.lang.StackOverflowError: null
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:773)
```

### Environment Information

- **Operating System**: Linux Mint
- **Micronaut Version:** 2.3.1
- **JDK Version:** 8

**Comment by sdelamo** [comment]
It is not an bug with Ldap. 

the issue is that you are attempting to serialize a 'UserDetails' object as JSON with Jackson and that it is not supported. 'UserDetails' has a method 'Optional<UserDetails> getUserDetails' which causes the infinite loop.

**Comment by sdelamo** [comment]
You will get the same error: 

```
Publisher<AuthenticationResponse> publisher = Flowable.create(emitter -> {
            emitter.onNext(new UserDetails("john", Collections.emptyList()));
            emitter.onComplete();
        }, BackpressureStrategy.ERROR);
        return Mono.fromDirect(publisher).map(HttpResponse::ok);
```
