### ISSUE TITLE
StackOverflowError When using Eureka With OpenIdProviderMetadata

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-security#634]
See: #623 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an Application with Eureka and OAuth2 Support and configure it to support OpenID Connect
2. Create a `EndSessionEndpoint` that takes a `OpenIdProviderMetadata` on the constructor
3. Start the application

### Expected Behaviour

Application Starts

### Actual Behaviour

Application fails to start with a StackOverflowError

```
[36m22:33:48.350[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.web.router.DefaultRouter]

Path Taken: new SomeSessionEndpoint(EndSessionCallbackUrlBuilder endSessionCallbackUrlBuilder,OauthClientConfiguration clientConfiguration,[OpenIdProviderMetadata providerMetadata]) --> DefaultOpenIdProviderMetadata.openIdConfiguration(OauthClientConfiguration 
...
Caused by: java.lang.StackOverflowError: null
	at java.base/java.lang.String.substring(String.java:1874)
	at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:256)
	at java.base/sun.net.www.protocol.file.Handler.parseURL(Handler.java:67)
```

### Environment Information

- **Operating System**: Debian 10
- **Micronaut Version:** 2.4.4
- **JDK Version:** openjdk version "11.0.2" 2019-01-15

### Example Application

- https://github.com/JasonTypesCodes/mn-eureka-oauth

To find the error:

```
$ ./gradlew run > out.txt
$ cat out.txt | grep -n "StackOverflowError"
```

The application will start successfully if you update `SomeSessionEndpoint` to no longer take in a `OpenIdProviderMetadata`

Removing the Eureka configuration will also avoid this error, but the application will probably still fail to start due to the configured openid issuer URL not existing.

**Comment by JasonTypesCodes** [comment]
This morning, @jameskleeh advised that injecting a `Provider` in the custom endpoint implementation.  It makes sense given that `AbstractEndSessionRequest` is requesting a Supplier rather than the instance itself.  I'll give that a try, and assuming everything works out (I think it will) I'll close this.  Thanks!
