### ISSUE TITLE
JWT Signature verification failed with JWK Set Keys (Key ID not found)

### ISSUE THREAD

**Issue by aleksey-dv** [micronaut-projects/micronaut-security#933]
### Expected Behavior

Hello!
I am trying set up odic authorization woth Keycloak in akhq (https://github.com/tchiotludo/akhq) wich based on micronaut 3.2.
My config:
```
micronaut:
  endpoints:
    loggers:
      enabled: true
      sensitive: false
      write-sensitive: false
  security:
    authentication: "idtoken"
    enabled: true
    oauth2:
      clients:
        keycloak:
          client-id: "akhq"
          client-secret: "<client-secret>"
          openid:
            issuer: "https://idm.keycloak.domain/auth/realms/myrealm"
            jwks-uri: " https://idm.keycloak.domain/auth/realms/myrealm/protocol/openid-connect/certs"
            token:
              auth-method: "client_secret_basic"
```

Keycloak JWKS json response (long fields shorten with `...`):
```
{
    "keys": [
        {
            "kid": "cHwCrM9OPVvXd3h7jnIesBVUsp517DFM6ZbTnPbd_sE",
            "kty": "RSA",
            "alg": "RS256",
            "use": "sig",
            "n": "olx2zJbtt...9vgeDenkAgtNWCi3ehQ",
            "e": "AQAB",
            "x5c": [
                "MIICrz...gA=="
            ],
            "x5t": "LAZH...qkM",
            "x5t#S256": "Pke95VKe80O...5kfQEz0oS_I"
        },
        {
            "kid": "mY6PxwhZgMoQ4t0gJqK0FC8_bzUDzGJwQEj56h28gRQ",
            "kty": "RSA",
            "alg": "RSA-OAEP",
            "use": "enc",
            "n": "lIN...rAQ",
            "e": "AQAB",
            "x5c": [
                "MIIC,,,IeA=="
            ],
            "x5t": "64TN...490",
            "x5t#S256": "3-96h...5ixIk"
        }
    ]
}
```

JWT token header:
```
{"alg":"RS256","typ" : "JWT","kid" : "cHwCrM9OPVvXd3h7jnIesBVUsp517DFM6ZbTnPbd_sE"}
```

### Actual Behaviour

Falied with:
```
2022-02-15 10:02:20,836 DEBUG pGroup-1-3 i.m.s.f.SecurityFilter     Authorized request GET /oauth/callback/keycloak. The rule provider org.akhq.modules.SecuredAnnotationRuleWithDefault authorized the request.
2022-02-15 10:02:20,838 TRACE pGroup-1-3 o.r.DefaultOauthController Received callback from oauth provider [keycloak]
2022-02-15 10:02:20,848 TRACE pGroup-1-3 .s.o.c.DefaultOpenIdClient Received a successful authorization response from provider [keycloak]
2022-02-15 10:02:20,849 TRACE pGroup-1-3 thorizationResponseHandler Validating state found in the authorization response from provider [keycloak]
2022-02-15 10:02:20,858 TRACE pGroup-1-3 DefaultTokenEndpointClient Sending request to token endpoint [https://idm.keycloak.domain/auth/realms/myrealm/protocol/openid-connect/token]
2022-02-15 10:02:20,861 TRACE pGroup-1-3 DefaultTokenEndpointClient The token endpoint supports [[client_secret_basic]] authentication methods
2022-02-15 10:02:20,863 TRACE pGroup-1-3 DefaultTokenEndpointClient Using client_secret_basic authentication. Adding an Authorization header
2022-02-15 10:02:20,898 TRACE pGroup-1-3 redentialsHttpClientFilter Did not find any OAuth 2.0 client which should decorate the request with an access token received from client credentials request
2022-02-15 10:02:21,076 TRACE pGroup-1-3 thorizationResponseHandler Token endpoint returned a success response. Validating the JWT
2022-02-15 10:02:21,077 TRACE pGroup-1-3 enIdTokenResponseValidator Validating the JWT signature using the JWKS uri [https://idm.keycloak.domain/auth/realms/myrealm/protocol/openid-connect/certs]
2022-02-15 10:02:21,119 DEBUG pGroup-1-3 i.m.s.t.j.v.JwtValidator   Validating signed JWT
2022-02-15 10:02:21,216 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature Key Type: RSA
2022-02-15 10:02:21,223 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature JWT Key ID: cHwCrM9OPVvXd3h7jnIesBVUsp517DFM6ZbTnPbd_sE
2022-02-15 10:02:21,230 ERROR pGroup-1-3 enIdTokenResponseValidator JWT signature validation failed for provider [keycloak]
2022-02-15 10:02:21,228 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature JWK Set Key IDs: xhashf6Mg7FZmp7dau0Tjb7Yv2V_B9fQRKTSQ9XFpec,y6cExeqcBYp3c2ShgJfPDXSfk_GGvvYtRqiFdUz4KUQ
2022-02-15 10:02:21,230 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature Found 0 matching JWKs
2022-02-15 10:02:21,230 DEBUG pGroup-1-3 i.m.s.t.j.v.JwtValidator   JWT Signature verification failed: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjSHdDck05T1BWdlhkM2g3am5JZXNCVlVzcDUxN0RGTTZaYlRuUGJkX3NFIn0.<jwt_token_body>.iFy6UGTxC6HkQlkhy7h0WUkHvMrVUjAxldf0WZ0kXl_-LEpvArwegDjBWCATjt0l1xXH-hHLL783rmDX64ovFWIzqGT7m4bQ15Bv72Ei0ANYIT2kyRYvEyidkI5m48HJ-nr3-PVTCB2oNLJxYtGQuLi4rLid39Z3XcbGk7a4liClY6tXjN_9Nq6GdoPJysyVC_nLWKzERCwGk9OtxB1Tg6e6A9vyzd_DgWzYMZnZsDNOmkAy80fMeU2PjWMCMry7lTpbtHtodg1zKCS_1iWVlSftNw22E-kkByk6SrShIfCIEZ693Zkv8d65b4pCkHPm--4kyoDkMlfWDgaEAY7UGQ
2022-02-15 10:02:21,230 TRACE pGroup-1-3 thorizationResponseHandler Token validation failed. Failing authentication
2022-02-15 10:02:21,240 ERROR r-thread-3 o.a.c.ErrorController      JWT validation failed
io.micronaut.security.authentication.AuthenticationException: JWT validation failed
        at io.micronaut.security.authentication.AuthenticationResponse.exception(AuthenticationResponse.java:121)
        at io.micronaut.security.oauth2.endpoint.authorization.response.DefaultOpenIdAuthorizationResponseHandler.lambda$createAuthenticationResponse$1(DefaultOpenIdAuthorizationResponseHandler.java:171)
        at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8402)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onNext(FluxSwitchMap.java:236)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.drain(FluxSwitchMap.java:355)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.innerNext(FluxSwitchMap.java:413)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapInner.onNext(FluxSwitchMap.java:512)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onNext(WebMetricsPublisher.java:180)
        at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onNext(WebMetricsPublisher.java:157)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.lambda$onNext$1(ClientServerRequestTracingPublisher.java:60)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onNext(ClientServerRequestTracingPublisher.java:60)
        at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onNext(ClientServerRequestTracingPublisher.java:52)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxCreate$NoOverflowBaseAsyncSink.next(FluxCreate.java:648)
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
        at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2405)
        at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2322)
        at io.micronaut.http.client.netty.DefaultHttpClient$SimpleChannelInboundHandlerInstrumented.channelRead0(DefaultHttpClient.java:3072)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:214)
        at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:189)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

The strangest part is 
```
2022-02-15 10:02:21,223 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature JWT Key ID: cHwCrM9OPVvXd3h7jnIesBVUsp517DFM6ZbTnPbd_sE
2022-02-15 10:02:21,230 ERROR pGroup-1-3 enIdTokenResponseValidator JWT signature validation failed for provider [keycloak]
2022-02-15 10:02:21,228 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature JWK Set Key IDs: xhashf6Mg7FZmp7dau0Tjb7Yv2V_B9fQRKTSQ9XFpec,y6cExeqcBYp3c2ShgJfPDXSfk_GGvvYtRqiFdUz4KUQ
2022-02-15 10:02:21,230 DEBUG pGroup-1-3 .m.s.t.j.s.j.JwksSignature Found 0 matching JWKs
```
there are not such keyIDs in JWKS json response, and this key ids doesn't seems normal (first starting with `xhash..`).

### Steps To Reproduce

run AKHQ 0.20.0 (micronaut 3.2) with micronaut-security config mentioned above

### Example Application

I've tested this JWT and JWKS json with small go snippet (https://gist.github.com/aleksey-dv/883cddb4b4742f2db488df8436cb3ad3) and it is work as expected

### Version

3.2.0

**Comment by aleksey-dv** [comment]
sorry, it was wrong keycloak cluster configuration 😅
